openapi: 3.0.4
info:
  title: Bestellservice-Microservice API
  description: API des BestellServices
  contact:
    email: ch.fries@gmx.net
  version: 0.0.1
externalDocs:
  description: Github-Repository
  url: https://github.com/ChFries/bestellservice
servers:
  - url: localhost.something
tags:
  - name: bestellung
    description: Bestellungen aufgeben, updaten und löschen
paths:
  /bestellung:
    get:
      tags:
        - bestellung
      summary: Alle Bestellungen abrufen
      description: Ruft alle Bestellungen ab
      operationId: getBestellung
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/BestellungDto"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
    post:
      tags:
        - bestellung
      summary: Bestellung anlegen
      description: Legt eine neue Bestellung an
      operationId: postBestellung
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BestellungDto'
      responses:
        '201':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BestellungDto'
        '400':
          description: Invalid input
        '422':
          description: Validation exception
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /bestellung/{bestellId}:
    get:
      tags:
        - bestellung
      summary: Bestellung abrufen
      description: Ruft eine Bestellung anhand der UUID ab
      operationId: getBestellungById
      parameters:
        - name: bestellId
          in: path
          description: ID der bestellung
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BestellungDto'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bestellung not found
    delete:
      tags:
        - bestellung
      summary: Bestellung löschen
      description: Löscht die Bestellung anhand der UUID
      operationId: deleteBestellungById
      parameters:
        - name: bestellId
          in: path
          description: ID der zu löschenden Bestellung
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: order deleted
        '400':
          description: Invalid ID supplied
        '404':
          description: Order not found
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorDto"
  /bestellung/{bestellId}/status:
    put:
      tags:
        - bestellung
      summary: Bestellstatus updaten
      description: Ändert den Status einer Bestellung
      operationId: updateZahlungsstatusById
      parameters:
        - name: bestellId
          in: path
          description: ID der bestellung
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/StatusUpdateDto'
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BestellungDto'
        '400':
          description: Invalid ID supplied
        '404':
          description: Bestellung not found

components:
  schemas:
    BestellungDto:
      $ref: '../common-schemas.yaml#/components/schemas/BestellungDto'
    BestellPositionDto:
      $ref: '../common-schemas.yaml#/components/schemas/BestellPositionDto'
    StatusDto:
      $ref: '../common-schemas.yaml#/components/schemas/StatusDto'
    StatusUpdateDto:
      $ref: '../common-schemas.yaml#/components/schemas/StatusUpdateDto'
    ErrorDto:
      $ref: '../common-schemas.yaml#/components/schemas/ErrorDto'


